esphome:
  name: hisense-tv-ir-controller
  platform: ESP8266
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret hass_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hisense_ir_ap_ssid
    password: !secret hisense_ir_ap_password

captive_portal:

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 70%

switch:
  - platform: template
    name: "Hisense TV IR Remote Controller"
    icon: "mdi:led-variant-on"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x00FD
          command: 0xB04F
          repeat:
            times: 1
            wait_time: 50ms
    turn_off_action:
      - remote_transmitter.transmit_nec:
          address: 0x00FD
          command: 0xB04F
          repeat:
            times: 1
            wait_time: 50ms
